Add support for the ARM64 architecture in the Docker images.
Also, update the JDK/JRE versions to 17 (LTS) in preparation for the upcoming Spring Boot v3.

Resolves #1029

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -18,20 +18,23 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Extract metadata to env variables
         uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1
 
       - name: Pull previous images to support caching
         run: |
-          docker pull $IMAGE_NAME:builder || echo "Previous builder image not found"
-          docker pull $IMAGE_NAME:latest || echo "Previous image not found"
+          docker pull $IMAGE_NAME:builder || >&2 echo "Previous builder image not found"
+          docker pull $IMAGE_NAME:latest || >&2 echo "Previous image not found"
 
-      - name: Build docker images for building and for distribution
-        run: |
-          docker build --cache-from=$IMAGE_NAME:builder --target builder -t $IMAGE_NAME:builder .
-          docker build --cache-from=$IMAGE_NAME:builder --cache-from=$IMAGE_NAME:latest -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_ID .
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+        with:
+          platforms: 'arm64'
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Login to Docker Hub
         uses: docker/login-action@v1
@@ -39,14 +42,34 @@ jobs:
           username: ${{ secrets.JORE4_DOCKERHUB_USER }}
           password: ${{ secrets.JORE4_DOCKERHUB_TOKEN }}
 
-      - name: Push image tagged with git commit details to Docker Hub
-        run: docker push $IMAGE_NAME:$COMMIT_ID
+      - name: Build and push image tagged with commit ID to Docker Hub
+        run: |
+          docker buildx build \
+            --push \
+            --platform linux/amd64,linux/arm64 \
+            --cache-from=$IMAGE_NAME:builder \
+            --cache-from=$IMAGE_NAME:latest \
+            -t $IMAGE_NAME:$COMMIT_ID \
+            .
 
-      - name: Push rest of the tags to Docker Hub
+      - name: Build and push :builder and :latest tag to Docker Hub
         if: ${{ github.ref == 'refs/heads/main' }}
         run: |
-          docker push $IMAGE_NAME:builder
-          docker push $IMAGE_NAME:latest
+          docker buildx build \
+            --push
+            --platform linux/amd64,linux/arm64 \
+            --target builder \
+            --cache-from=$IMAGE_NAME:builder \
+            -t $IMAGE_NAME:builder \
+            .
+
+          docker buildx build \
+            --push \
+            --platform linux/amd64,linux/arm64 \
+            --cache-from=$IMAGE_NAME:builder \
+            --cache-from=$IMAGE_NAME:latest \
+            -t $IMAGE_NAME:latest \
+            .
 
   run_e2e_tests:
     needs: push_to_registry
